on: push
name: Test
jobs:
  test:
    name: Test
    runs-on: macOS-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=13.3,name=iPhone 11']
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Dependecies
        run:
          pod install
      - name: Build and test
        run: |
          xcodebuild clean test -workspace HowTo.xcworkspace -scheme HowTo -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
        env: 
         destination: ${{ matrix.destination }}
